"""add household food inventory

Revision ID: 22449003ba36
Revises: b3f1c9a27d84
Create Date: 2026-09-07 04:50:30.116224

"""

import sqlalchemy as sa
from alembic import op

import mealie.db.migration_types

# revision identifiers, used by Alembic.
revision = "22449003ba36"
down_revision: str | None = "b3f1c9a27d84"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "household_food_inventory",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("group_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("household_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("food_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("unit_id", mealie.db.migration_types.GUID(), nullable=True),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.CheckConstraint("quantity >= 0", name="household_food_inventory_quantity_non_negative"),
        sa.ForeignKeyConstraint(["food_id"], ["ingredient_foods.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["unit_id"], ["ingredient_units.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("household_id", "food_id", name="household_food_inventory_household_id_food_id_key"),
    )
    with op.batch_alter_table("household_food_inventory", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_household_food_inventory_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_household_food_inventory_food_id"), ["food_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_household_food_inventory_group_id"), ["group_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_household_food_inventory_household_id"), ["household_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_household_food_inventory_unit_id"), ["unit_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("household_food_inventory", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_household_food_inventory_unit_id"))
        batch_op.drop_index(batch_op.f("ix_household_food_inventory_household_id"))
        batch_op.drop_index(batch_op.f("ix_household_food_inventory_group_id"))
        batch_op.drop_index(batch_op.f("ix_household_food_inventory_food_id"))
        batch_op.drop_index(batch_op.f("ix_household_food_inventory_created_at"))

    op.drop_table("household_food_inventory")
    # ### end Alembic commands ###
